---
stages:
- name: Deploy App
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Push to Bluemix
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |
      DOMAIN=$(cf domains | grep -m 1 shared | awk '{print $1}')
      cf push -m 1G "${CF_APP}"
      cf map-route "${CF_APP}" ${DOMAIN} -n "${CF_APP}"-pm
